name: Test Installation

on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: dev-environment.yml
          activate-environment: nessie-dev
          use-mamba: true
      
      - name: Install package
        run: mamba run -n nessie-dev pip install .

      - name: Test import
        run: mamba run -n nessie-dev python -c "import nessie" 
